# è¯·ä½¿ç”¨æœ€æ–°ç‰ˆClash
# å°†proxy-providersé‡Œé¢é“¾æ¥ä¸­çš„â€œä½ çš„è®¢é˜…é“¾æ¥â€å…¨éƒ¨æ›¿æ¢å³å¯
port: 7890
mixed-port: 7891
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090


proxy-providers:

  #å…¨éƒ¨èŠ‚ç‚¹
  All:
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=ä½ çš„è®¢é˜…é“¾æ¥&list=true&udp=true"
    # å¯ä»¥ä½¿ç”¨ä»»æ„ç±»å‹çš„é“¾æ¥æ›¿æ¢ä¸Šé¢æ–‡å­—ï¼Œå¤šä¸ªé“¾æ¥ä½¿ç”¨è‹±æ–‡ç¬¦å·çš„ç«–æ |éš”å¼€ä¸€èµ·å†™ä¸Šå³å¯ï¼›ä¹Ÿå¯ä»¥å°†Clashè®¢é˜…é“¾æ¥æ›¿æ¢æ‰æ•´ä¸ªå¼•å·""å†…çš„é“¾æ¥
    interval: 3600
    path: ./all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  #é¦™æ¸¯èŠ‚ç‚¹     
  HK:
    type: file
    path: ./all.yaml
    filter: é¦™|æ¸¯|é¦™æ¸¯|é¦™æ±Ÿ|é¦™å²›|HK|Hong
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204

  #æ—¥æœ¬èŠ‚ç‚¹
  JP:
    type: file
    path: ./all.yaml
    filter: æ—¥|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204

  #ç¾å›½èŠ‚ç‚¹
  US:
    type: file
    path: ./all.yaml
    filter: ç¾|ç¾å›½|ç¾åˆ©åšåˆä¼—å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States|States|American
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204

  #å°æ¹¾èŠ‚ç‚¹
  TW:
    type: file
    path: ./all.yaml
    filter: å°|å°æ¹¾|å°åŒ—|æ–°åŒ—|æ¡ƒå›­|å°ä¸­|å°å—|é«˜é›„|åŸºéš†|æ–°ç«¹|å˜‰ä¹‰|è‹—æ —|å½°åŒ–|å—æŠ•|äº‘æ—|å±ä¸œ|å°ä¸œ|èŠ±è²|å®œå…°|æ¾æ¹–|é‡‘é—¨|è¿æ±Ÿ|TW|Taiwan
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204

  #ç‹®åŸèŠ‚ç‚¹
  SG:
    type: file
    path: ./all.yaml
    filter: æ–°|ç‹®|ç…|å¡|æ–°åŠ å¡|æ˜Ÿ|æ˜ŸåŠ å¡|æ˜Ÿæ´²|ç‹®åŸ|SG|Singapore
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204

  #è‹±å›½èŠ‚ç‚¹
  UK:
    type: file
    path: ./all.yaml
    filter: è‹±|è‹±å›½|è‹±æ ¼å…°|ä¸åˆ—é¢ |è‹±è”é‚¦|æ—¥ä¸è½å¸å›½|ä¼¦æ•¦|ä¼¯æ˜ç¿°|åˆ©å…¹|æ ¼æ‹‰æ–¯å“¥|è°¢è²å°”å¾·|æ›¼å½»æ–¯ç‰¹|çˆ±ä¸å ¡|åˆ©ç‰©æµ¦|UK|United
      Kingdom|British|Britisher
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204

  #éŸ©å›½èŠ‚ç‚¹
  KR:
    type: file
    path: ./all.yaml
    filter: éŸ©|éŸ©å›½|å—éŸ©|å—æœé²œ|é«˜ä¸½|å¤§éŸ©æ°‘å›½|é¦–å°”|ä¸–å®—|æµå·å¸‚|æ°´åŸ|é‡œå±±|å¤§é‚±|ä»å·|å…‰å·|å¤§ç”°|è”šå±±|KR|Korea|Korean|South
      Korea
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204


dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 8.8.8.8
    - 8.8.4.4:53
    - 119.28.28.28
    - 114.114.114.114
    - 202.141.176.93
    - 202.141.178.13
    - 117.50.10.10
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - https://dns.google/dns-query
    - https://doh.dns.apple.com/dns-query
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.hinet.net/dns-query
    - https://ordns.he.net/dns-query
    - https://doh.dns.sb/dns-query


proxies:


proxy-groups:

  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    use:
      - All
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ›‘ å…¨çƒæ‹¦æˆª

  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    use:
      - All
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 1

  - name: ğŸ¬ æ²¹ç®¡è§†é¢‘
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ›‘ å…¨çƒæ‹¦æˆª

  - name: ğŸ“¹ å¥ˆé£å¨±ä¹
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ›‘ å…¨çƒæ‹¦æˆª

  - name: ğŸ“² ç”µæŠ¥ä¿¡æ¯
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ›‘ å…¨çƒæ‹¦æˆª

  - name: ğŸ“¢ è°·æ­ŒFCM
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ›‘ å…¨çƒæ‹¦æˆª

  - name: ğŸŒ å›½å¤–ç½‘ç«™
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ›‘ å…¨çƒæ‹¦æˆª

  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ›‘ å…¨çƒæ‹¦æˆª

  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ›‘ å…¨çƒæ‹¦æˆª

  - name: ğŸ¶ ç½‘æ˜“éŸ³ä¹
    type: select
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ›‘ å…¨çƒæ‹¦æˆª

  - name: ğŸ“º å“”å“©å“”å“©
    type: select
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ›‘ å…¨çƒæ‹¦æˆª

  - name: ğŸ® æ¸¸æˆå¹³å°
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ›‘ å…¨çƒæ‹¦æˆª

  - name: ğŸŒ å›½å†…ç½‘ç«™
    type: select
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ›‘ å…¨çƒæ‹¦æˆª

  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ›‘ å…¨çƒæ‹¦æˆª

  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    type: url-test
    use:
      - HK
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 1

  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    type: url-test
    use:
      - JP
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 1

  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
    type: url-test
    use:
      - TW
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 1

  - name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    type: url-test
    use:
      - US
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 1

  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
    type: url-test
    use:
      - SG
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 1

  - name: ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
    type: url-test
    use:
      - UK
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 1

  - name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
    type: url-test
    use:
      - KR
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 1

  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - DIRECT
      - REJECT

  - name: ğŸ›‘ å…¨çƒæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - DIRECT

  - name: ğŸ† AdBlock
    type: select
    proxies:
      - REJECT
      - DIRECT


rule-providers:

  Lan:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml"
    path: ./ruleset/Lan.yaml
    interval: 86400

  Direct:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.yaml"
    path: ./ruleset/direct.yaml
    interval: 86400

  adblock:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical.yaml"
    path: ./ruleset/Advertising_Classical.yaml
    interval: 86400

  Hijacking:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hijacking/Hijacking.yaml"
    path: ./ruleset/Hijacking.yaml
    interval: 86400

  Privacy:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy_Classical.yaml"
    path: ./ruleset/Privacy_Classical.yaml
    interval: 86400

  EasyPrivacy:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EasyPrivacy/EasyPrivacy_Classical.yaml"
    path: ./ruleset/EasyPrivacy_Classical.yaml
    interval: 86400

  GitHub:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml"
    path: ./ruleset/GitHub.yaml
    interval: 86400

  YouTube:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"
    path: ./ruleset/YouTube.yaml
    interval: 86400

  Netflix:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml"
    path: ./ruleset/Netflix.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
    path: ./ruleset/Telegram.yaml
    interval: 86400

  GoogleFCM:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.yaml
    path: ./ruleset/GoogleFCM.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml"
    path: ./ruleset/Apple.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml"
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  NetEaseMusic:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.yaml"
    path: ./ruleset/NetEaseMusic.yaml
    interval: 86400

  BiliBili:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml"
    path: ./ruleset/BiliBili.yaml
    interval: 86400

  ZhihuAds:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ZhihuAds/ZhihuAds.yaml"
    path: ./ruleset/ZhihuAds.yaml
    interval: 86400

  Game:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml"
    path: ./ruleset/Game.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Classical.yaml"
    path: ./ruleset/China_Classical.yaml
    interval: 86400

  Global_Classical:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/Global/Global_Classical.yaml"
    path: ./ruleset/Global_Classical.yaml
    interval: 86400


rules:
# ç­–ç•¥ç»„
  - RULE-SET,Lan,DIRECT
  - RULE-SET,Direct,DIRECT
  - RULE-SET,adblock,ğŸ† AdBlock
  - RULE-SET,Hijacking,ğŸ† AdBlock
  - RULE-SET,Privacy,ğŸ† AdBlock
  - RULE-SET,EasyPrivacy,ğŸ† AdBlock
  - RULE-SET,GitHub,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - RULE-SET,YouTube,ğŸ¬ æ²¹ç®¡è§†é¢‘
  - RULE-SET,Netflix,ğŸ“¹ å¥ˆé£å¨±ä¹
  - RULE-SET,Telegram,ğŸ“² ç”µæŠ¥ä¿¡æ¯
  - RULE-SET,GoogleFCM,ğŸ“¢ è°·æ­ŒFCM
  - RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,NetEaseMusic,ğŸ¶ ç½‘æ˜“éŸ³ä¹
  - RULE-SET,BiliBili,ğŸ“º å“”å“©å“”å“©
  - RULE-SET,ZhihuAds,ğŸ† AdBlock
  - RULE-SET,Game,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,China,ğŸŒ å›½å†…ç½‘ç«™
  - RULE-SET,Global_Classical,ğŸŒ å›½å¤–ç½‘ç«™
# è‡ªç”¨é…ç½®
  - DOMAIN-SUFFIX,raw.githubusercontent.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,raw.ev2.workers.dev,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,adtchrome.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,deepl.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,translate.googleapis.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,gitlab.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,github.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,ipm-provider.ff.avast.com,REJECT
  - DOMAIN-SUFFIX,ccleaner.com,REJECT
  - DOMAIN-SUFFIX,mypikpak.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,update.aida64.com,REJECT
  - DOMAIN-SUFFIX,dmm.co.jp,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  - DOMAIN-SUFFIX,rutracker.org,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  - DOMAIN-SUFFIX,zooqle.com,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  - DOMAIN-SUFFIX,byrut.org,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  - DOMAIN-SUFFIX,rarbgprx.org,ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  - DOMAIN-SUFFIX,imagehaha.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,98tuch.net,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,xcimg.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,rysuanaaser.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,update.chuyu.me,REJECT
  - DOMAIN-SUFFIX,gfwsl.geforce.com,REJECT
  - DOMAIN-SUFFIX,bugutv.cn,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,xmkczs.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,oook.xyz,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,6678888.xyz,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,0daydown.com,DIRECT
  - DOMAIN-SUFFIX,license.piriform.com,REJECT
  - DOMAIN-SUFFIX,115.com,DIRECT
  - DOMAIN-SUFFIX,pianyuanw.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,yinfans.me,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,yinfans.net,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,pianyuan.org,DIRECT
  - DOMAIN-SUFFIX,aibaipiao01.com,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,huorong.cn,DIRECT
  - DOMAIN-SUFFIX,itsk.com,DIRECT
  - DOMAIN-SUFFIX,y5y4.com,DIRECT
  - DOMAIN-SUFFIX,mimei520.com,DIRECT
  - DOMAIN-SUFFIX,pianyuan.la,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,sehuatang.net,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DOMAIN-SUFFIX,aibaipiao.life,â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,fe80::/10,DIRECT
  - IP-CIDR,119.28.28.28/32,DIRECT
  - IP-CIDR,182.254.116.0/24,DIRECT
  - GEOIP,CN,ğŸŒ å›½å†…ç½‘ç«™
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
