proxy-providers:
  HK:
    type: http
    path: ./Server/hk.yaml
    url: "è¿™é‡Œå¡«å†™ä½ çš„è®¢é˜…é“¾æ¥ï¼Œæ³¨æ„ä¿ç•™åŒå¼•å·å’ŒåŒå¼•å·å‰é¢çš„ç©ºæ ¼"
    interval: 3600
    filter: 'é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  SG:
    type: http
    path: ./Server/sg.yaml
    url: "è¿™é‡Œå¡«å†™ä½ çš„è®¢é˜…é“¾æ¥ï¼Œæ³¨æ„ä¿ç•™åŒå¼•å·å’ŒåŒå¼•å·å‰é¢çš„ç©ºæ ¼"
    interval: 3600
    filter: 'æ–°åŠ å¡|ç‹®åŸ|SG|Singapore|ğŸ‡¸ğŸ‡¬'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  KR:
    type: http
    path: ./Server/kr.yaml
    url: "è¿™é‡Œå¡«å†™ä½ çš„è®¢é˜…é“¾æ¥ï¼Œæ³¨æ„ä¿ç•™åŒå¼•å·å’ŒåŒå¼•å·å‰é¢çš„ç©ºæ ¼"
    interval: 3600
    filter: 'éŸ©å›½|éŸ“åœ‹|å—æœé²œ|KR|Korean|ğŸ‡°ğŸ‡·'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  US:
    type: http
    path: ./Server/US.yaml
    url: "è¿™é‡Œå¡«å†™ä½ çš„è®¢é˜…é“¾æ¥ï¼Œæ³¨æ„ä¿ç•™åŒå¼•å·å’ŒåŒå¼•å·å‰é¢çš„ç©ºæ ¼"
    interval: 3600
    filter: 'ç¾å›½|US|USA|America|United States|ğŸ‡ºğŸ‡¸'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  JP:
    type: http
    path: ./Server/JP.yaml
    url: "è¿™é‡Œå¡«å†™ä½ çš„è®¢é˜…é“¾æ¥ï¼Œæ³¨æ„ä¿ç•™åŒå¼•å·å’ŒåŒå¼•å·å‰é¢çš„ç©ºæ ¼"
    interval: 3600
    filter: 'æ—¥æœ¬|JP|Japan|ğŸ‡¯ğŸ‡µ'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
mixed-port: 7890
allow-lan: false
mode: rule
log-level: debug
ipv6: false

proxy-groups:
  - name: å…¨çƒåŠ é€Ÿ
    type: select
    proxies:
      - é¦™æ¸¯èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - éŸ©å›½èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - DIRECT
  - name: ç”µæŠ¥ä¿¡æ¯
    type: select
    proxies:
      - é¦™æ¸¯èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - éŸ©å›½èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
  - name: Emby
    type: select
    proxies:
      - é¦™æ¸¯èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - éŸ©å›½èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - DIRECT
  - name: æ²¹ç®¡è§†é¢‘
    type: select
    proxies:
      - é¦™æ¸¯èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - éŸ©å›½èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
  - name: å›½é™…åª’ä½“
    type: select
    proxies:
      - é¦™æ¸¯èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - éŸ©å›½èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
  - name: æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - é¦™æ¸¯èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - éŸ©å›½èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - DIRECT
  - name: "é¦™æ¸¯èŠ‚ç‚¹"
    type: url-test
    use:
      - HK
  - name: "ç‹®åŸèŠ‚ç‚¹"
    type: url-test
    use:
      - SG
  - name: "éŸ©å›½èŠ‚ç‚¹"
    type: url-test
    use:
      - KR
  - name: "æ—¥æœ¬èŠ‚ç‚¹"
    type: url-test
    use:
      - JP
  - name: "ç¾å›½èŠ‚ç‚¹"
    type: url-test
    use:
      - US

rule-providers:
   å¹¿å‘Šæ‹¦æˆª:
    type: http
    behavior: domain
    path: ./RuleSet/BanAD.yaml
    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/BanAD.yaml
    interval: 86400

   åº”ç”¨å‡€åŒ–:
    type: http
    behavior: classical
    path: ./RuleSet/BanProgramAD.list
    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/BanProgramAD.yaml
    interval: 86400

   Emby:
    type: http
    behavior: classical
    path: ./RuleSet/Emby.yaml
    url: https://cdn.jsdelivr.net/gh/iEwha/Profiles@master/Clash/Ruleset/Emby.yaml
    interval: 86400

   YouTube:
    type: http
    behavior: classical
    path: ./RuleSet/YouTube.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml
    interval: 86400

   Telegram:
    type: http
    behavior: classical
    path: ./RuleSet/Telegram.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml
    interval: 86400

   ChinaMedia:
    type: http
    behavior: classical
    path: ./RuleSet/ChinaMedia.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaMedia/ChinaMedia.yaml
    interval: 86400
 
   GlobalMedia:
    type: http
    behavior: classical
    path: ./RuleSet/GlobalMedia.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia.yaml
    interval: 86400

   Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Global/Global.yaml
    interval: 86400

   China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/China/China.yaml
    interval: 86400

rules:
  - RULE-SET,å¹¿å‘Šæ‹¦æˆª,REJECT
  - RULE-SET,åº”ç”¨å‡€åŒ–,REJECT
  - RULE-SET,Emby,Emby
  - RULE-SET,Telegram,ç”µæŠ¥ä¿¡æ¯
  - RULE-SET,YouTube,æ²¹ç®¡è§†é¢‘
  - RULE-SET,ChinaMedia,DIRECT
  - RULE-SET,GlobalMedia,å›½é™…åª’ä½“
  - RULE-SET,Global,å…¨çƒåŠ é€Ÿ
  - RULE-SET,China,DIRECT
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,æ¼ç½‘ä¹‹é±¼
   
