name: alpha87-Loon-Profiles-sync
on:
  schedule:
    - cron: '45 */24 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-alpha87-Loon-Profiles
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync alpha87-Loon-Profiles
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/alpha87/Loon-Profiles.git"
          source_branch: "master"
          destination_branch: "alpha87-Loon-Profiles"
          github_token: ${{ secrets.PAT }}